detectors:
- name: jplag
  config:
    language: cpp
    token_length: 8
    base_path: base
    suffixes: [".tpp", ".cpp"]
    # Optimization: Enable token normalization (catches variable renaming)
    normalize: true
    # Optimization: Enable match merging (catches obfuscation)
    match_merging: true
    gap_size: 6
    neighbor_length: 2
    overwrite: true


outputs:
- name: csv
  config:
    min_score: 0
    include_unique_names: true
- name: json
  config:
    pretty: true

processors:
  pre_detection:
    - name: encoding_normalizer
      config:
        extensions: [tpp, cpp]
  post_detection: []

settings:
  cleanup_temp: false
  verbose: true
  target_paths:
    - ./section1/labwork3-Odd/
  base_path: base
